name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./ml_data_pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Project Environment
        uses: ./.github/actions/setup

      - name: Install Dependencies
        run: poetry install
        working-directory: ./ml_data_pipeline

      - name: Run Tests
        run: poetry run invoke test

      - name: Run Linting
        run: poetry run invoke lint

      # - name: Run Typing Checks
      #   run: poetry run invoke type
